// resources/inertia/react/Card.jsx
import React from 'react'

export function W4Card({
  variant = 'base-100',
  size = 'md',
  bordered = false,
  borderedVariant = null,
  elevated = false,
  ghost = false,
  className = '',
  children,
  ...props
}) {
  const classes = [
    'w4-card',
    `w4-card-${variant}`,
    `w4-card-${size}`,
    bordered ? 'w4-card-bordered' : null,
    borderedVariant ? `w4-card-bordered-${borderedVariant}` : null,
    elevated ? 'w4-card-elevated' : null,
    ghost ? 'w4-card-ghost' : null,
    className || null,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={classes} {...props}>
      <div className="w4-card-body">{children}</div>
    </div>
  )
}

// resources/inertia/vue/Card.vue
<template>
  <div :class="classes">
    <div class="w4-card-body">
      <slot />
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  variant: { type: String, default: 'base-100' },
  size: { type: String, default: 'md' },
  bordered: { type: Boolean, default: false },
  borderedVariant: { type: String, default: null },
  elevated: { type: Boolean, default: false },
  ghost: { type: Boolean, default: false },
})

const classes = computed(() => {
  const c = ['w4-card', `w4-card-${props.variant}`, `w4-card-${props.size}`]

  if (props.bordered) c.push('w4-card-bordered')
  if (props.borderedVariant) c.push(`w4-card-bordered-${props.borderedVariant}`)
  if (props.elevated) c.push('w4-card-elevated')
  if (props.ghost) c.push('w4-card-ghost')

  return c
})
</script>
