// resources/inertia/react/Toggle.jsx
import React from 'react'

export function W4Toggle({
  checked = false,
  onChange,
  variant = 'default',
  size = 'md',
  name = null,
  disabled = false,
  readonly = false,
  invalid = false,
  valid = false,
  loading = false,
  className = '',
  ...props
}) {
  const classes = [
    'w4-toggle',
    `w4-toggle-${variant}`,
    `w4-toggle-${size}`,
    checked ? 'w4-toggle-checked' : null,
    disabled ? 'w4-toggle-disabled' : null,
    readonly ? 'w4-toggle-readonly' : null,
    invalid ? 'w4-toggle-invalid' : null,
    valid ? 'w4-toggle-valid' : null,
    loading ? 'w4-toggle-loading' : null,
    className || null,
  ]
    .filter(Boolean)
    .join(' ')

  const isDisabled = disabled || loading

  return (
    <input
      type="checkbox"
      name={name || undefined}
      className={classes}
      checked={checked}
      disabled={isDisabled}
      readOnly={readonly}
      onChange={onChange}
      {...props}
    />
  )
}

// resources/inertia/vue/Toggle.vue
<template>
  <input
    type="checkbox"
    :name="name || undefined"
    :class="classes"
    :disabled="isDisabled"
    :readonly="readonly"
    :checked="modelValue"
    @change="$emit('update:modelValue', $event.target.checked)"
  />
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  variant: { type: String, default: 'default' },
  size: { type: String, default: 'md' },
  name: { type: String, default: null },
  disabled: { type: Boolean, default: false },
  readonly: { type: Boolean, default: false },
  invalid: { type: Boolean, default: false },
  valid: { type: Boolean, default: false },
  loading: { type: Boolean, default: false },
})

defineEmits(['update:modelValue'])

const isDisabled = computed(() => props.disabled || props.loading)

const classes = computed(() => {
  const c = ['w4-toggle', `w4-toggle-${props.variant}`, `w4-toggle-${props.size}`]

  if (props.modelValue) c.push('w4-toggle-checked')
  if (props.disabled) c.push('w4-toggle-disabled')
  if (props.readonly) c.push('w4-toggle-readonly')
  if (props.invalid) c.push('w4-toggle-invalid')
  if (props.valid) c.push('w4-toggle-valid')
  if (props.loading) c.push('w4-toggle-loading')

  return c
})
</script>
