// resources/inertia/vue/Badge.vue
<template>
  <span :class="classes">
    <slot />
  </span>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  variant: { type: String, default: 'default' },
  size: { type: String, default: 'md' },
  outline: { type: Boolean, default: false },
  soft: { type: Boolean, default: false },
})

const classes = computed(() => {
  const c = ['w4-badge', `w4-badge-${props.variant}`, `w4-badge-${props.size}`]

  if (props.outline) c.push('w4-badge-outline')
  if (props.soft) c.push('w4-badge-soft')

  return c
})
</script>

// resources/inertia/react/Badge.jsx
import React from 'react'

export function W4Badge({ variant = 'default', size = 'md', outline = false, soft = false, className = '', children, ...props }) {
  const classes = [
    'w4-badge',
    `w4-badge-${variant}`,
    `w4-badge-${size}`,
    outline ? 'w4-badge-outline' : null,
    soft ? 'w4-badge-soft' : null,
    className || null,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <span className={classes} {...props}>
      {children}
    </span>
  )
}
